title: sisfok
email: sisfok.uh@gmail.com
description: web sisfok ini untuk tempat belajar
baseurl: ""
url: "https://sisfok.github.io/"
github_username: deovaliandro

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-mentions
  - jekyll-avatar

jekyll-mentions:
  base_url: https://github.com

destination: ./public
markdown: kramdown
highlighter: rouge