title: sisfok
email: sisfok.uh@gmail.com
description: web sisfok ini untuk tempat belajar
baseurl: ""
url: "https://sisfok.github.io/"
github_username: deovaliandro

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-toc

destination: ./public
markdown: kramdown
highlighter: rouge