title: sisfok
email: deo@duck.com
description: Rho Chi
baseurl: ""
url: "https://sisfok.github.io/"
github_username: sisfok

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-mentions
  - jekyll-avatar

markdown: kramdown
highlighter: rouge

exclude: ['README.md', '*/README.md']

sass:
  style: compressed