title: sisfok
email: sisfok.uh@gmail.com
description: web sisfok ini untuk tempat belajar
baseurl: ""
url: "https://sisfok.github.io/"
github_username: deovaliandro

plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-mentions
  - jekyll-avatar

jekyll-mentions:
  base_url: https://github.com

destination: ./public
markdown: kramdown
highlighter: rouge

collections_dir: labs
collections:
  pp-java:
    directory: /labs/_pp-java/
    order:
      - struktur-dasar.md
      - io.md
      - tipe-data.md
      - operasi.md
      - penyeleksian.md
      - perulangan.md
      - jump-statement.md
      - array.md
      - method.md
      - exceptions.md
      - file-io.md
    output: true
    permalink: /:collection/:name
  pbo-java:
    directory: /labs/pbo-java/
    output: true
    permalink: /:collection/:name