:page-title: Python101
:page-layout: default
:page-signed-by: Deo <valiandrod@gmail.com>, BobChrismansyah <bob@ilkom.my.id>
:page-math: true

:toc:

Python adalah bahasa pemrograman *high-level* yang mudah dipelajari dan
merupakan bahasa yang poweful. Dalam tulisan ini, kami akan menggunakan
Python 3.11.

== hello world

[source, python]
print("Meoworld!")

== variabel

Nama variabel haruslah ##lowercase##, jika lebih dari satu kata maka dipisahkan
dengan kbd:[_]. Hindari menggunakan nama variabel yang ambigu.

Contoh yang baik:

[source, python]
----
price = 12000
age = 12
new_address = "Makassar"
----

== tipe data

=== bilangan

Python bersifat strongly typed dan dynamic typed.

[source, python]
----
print(type(10))
print(type(3.14)
print(type(1j)
----

Menghasilkan:

[source, bash]
----
<class 'int'>
<class 'float'>
<class 'complex'>
----

=== string

String pada dasarnya adalah list sehingga char adalah string dgn panjang 1.
Karena merupakan list, maka segala jenis operasi array dapat digunakan.

[source, python]
----
name = "Deo Valiandro"
print(name[1])
print(name[:3])
----

=== list

List adalah array dalam Python. List tidak harus memiliki tipe data yang sama.

[source, python]
data = [1, 2.2, "name"]

=== tuple

Mirip dengan list kecuali datanya tidak bisa diubah.

[source, python]
student_identity = ("Deo", 25, 165)

== Konversi data

Python bersifat duck typing language.

== Input

Menggunakan fungsi `input()`. Misalnya:

[source, python]
----
name = input("Input name : ")
----

== Operator

. Arithmetic Operators
+
Operator aritmatik digunakan untuk menjalankan operasi matematika seperti
`+`, `-`, `\*`, `/`, `%`, `/` dan `**`.
+
[source, python]
----
# penjumlahan
result = 1 + 2

# modulus
result = 10 % 3

# floor division
result = 10 // 3

# pangkat
result = 2 ** 2

# akar
math.sqrt(4)
----

. Comparison (Relational) Operators
+
Operator komparasi digunakan untuk membandingkan value dan akan mengembalikan
nilai True atau False berdasarkan kondisinya. Operatornya adalah `>`, `<`, `>=`,
`<=`, `==` dan `!=`.
+
[source, pyton]
----
print(12 > 5)
----

. Logical (Boolean) Operators
+
Memuat operator logika `and`, `or` dan `not`.
+
[source, python]
----
print(true and true)
----

. Bitwise Operators
+
Operator bitwise bertindak pada operand seolah-olah mereka adalah string
digit binary.
+
Pada tabel di bawah : misalkan x = 10 (0000 1010) dan y = 4 (0000 0100)
+
[%autowidth]
|===
| Operator | Arti                | Contoh

| &        | Bitwise AND         | x & y = 0 (0000 0000)
| \|       | Bitwise OR          | x \| y = 14 (0000 1110)
| ~        | Bitwise NOT         | ~x = -11 (1111 0101)
| ^        | Bitwise XOR         | x ^ y = 14 (0000 1110)
| >>       | Bitwise right shift | x >> 2 = 2 (0000 0010)
| <<       | Bitwise left shift  | x << 2 = 40 (0010 1000)
|===

. Assignment Operators
+
Operator assignment digunakan dalam Python untuk menetapkan nilai ke
variable.
+
[%autowidth]
|===
| Operator | Arti

| =        | x = 5
| +=       | x += 5
| -=       | x -= 5
| *=       | x *= 5
| /=       | x /= 5
| %=       | x %= 5
| //=      | x //= 5
| **=      | x **= 5
| &=       | x &= 5
| \|=      | x \|= 5
| ^=       | x ^= 5
| >>=      | x >>= 5
| <<=      | x <<= 5
|===

. Identity Operator
+
[%autowidth]
|===
| Operator | Arti                            | Contoh

| is       | True jika kedua operand identik | x is True
| is not   | True jika operand tidak identik | x is not True
|===

. Membership Operator
+
[%autowidth]
|===
| Operator | Arti                                           | Contoh

| in | True jika value/variable ditemukan dalam collections | x in True
| not in | True jika value/variable tidak ditemukan dalam collection 
| x not in True
|===

