= RSA

== Introduction

RSA adalah sebuah algoritma berdasarkan skema public-key cryptography. Diberi
nama RSA sebagai inisial para penemunya: Ron Rivest, Adi Shamir, dan Leonard
Adleman. RSA dibuat di MIT pada tahun 1977 dan dipatenkan oleh MIT pada tahun
1983. Setelah bulan September tahun 2000, paten tersebut berakhir, sehingga saat
ini semua orang dapat menggunakannya dengan bebas.

RSA adalah algoritma yang mudah untuk diimplementasikan dan dimengerti.
Algoritma RSA adalah sebuah aplikasi dari sekian banyak teori seperti extended
euclid algorithm, euler's function sampai fermat theorem.

== Public-Key Cryptography

Konsep fundamental dari Public-Key Cryptography ditemukan oleh Whitfield Diffie
dan Martin Hellman, dan secara terpisah oleh Ralph Merkle.

Sedangkan konsep dasar Public-Key Cryptography terletak pada pemahaman bahwa
keys selalu berpasangan: encryption key dan decryption key. Juga perlu diingat
bahwa sebuah key tidak dapat digenerate dari key lainnya. Pemahaman encryption
dan decryption key sering disebut sebagai public dan private key. Seseorang
harus memberikan public key-nya agar pihak lain dapat meng-encrypt sebuah pesan.
Decryption hanya terjadi jika seseorang mempunyai private key.

Penggunaan algoritma ini harus memenuhi kriteria berikut.

1. Memungkinkan untuk mencari nilai e, d, n sedemikian rupa sehingga M^e atau
M^d mod n = M untuk semua M < n. 2. Relatif mudah untuk menghitung nilai M^e mod
n dan C^d mod n untuk semua nilai M < n. 3. Tidak memungkinkan mencari nilai d
jika diberikan nilai n dan e.

Syarat nilai e dan d ini, gcd(d,e)=1

sebelum memulai penggunaan RSA ini, terlebih dahulu kita harus memiliki bahan–
bahan dasar sebagai berikut:

1. p, q = 2 bilangan prima yang dirahasiakan 2. n, dari hasil p.q 3. e, dengan
ketentuan gcd (phi(n), e) =1 4. d, e^-1 (mod phi(n))

== Scenario

Bagian ini menjelaskan skenario bagaimana public-key cryptosystem bekerja. Saya
akan menggunakan partisipan klasik Alice dan Bob sebagai orang-orang yang
melakukan pertukaran informasi.

  1. Alice dan Bob setuju untuk menggunakan public-key cryptosystem.

  2. Bob mengirimkan public key-nya kepada Alice.

  3. Alice meng-encrypt pesan yang dibuatkan dengan menggunakan public
     key milik Bob dan mengirimkan pesan yang sudah di-encrypt kepada Bob.

  4. Bob men-decrypt pesan dari Alice menggunakan private key
     miliknya.

== Rumus Dasar Terdapat dua rumus utama dari RSA, yaitu :

[source, bash]
---
C = M^e mod n (fungsi enkripsi) M = C^d mod n (fungsi dekripsi)
---

dimana :

* C = Cipherteks
* M = Message
* e = kunci publik
* d = kunci privat
* n = modulo pembagi(akan dijelaskan lebih lanjut )

== Key Generation

Misalkan Alice ingin Bob mengirimnya sebuah pesan melalui jalur yang aman. Alice
akan memberikan public keynya kepada Bob dan menyimpan private key untuk
dirinya.

1. Pilih 2 bilangan prima, misalnya p = 17 dan q = 11.

2. Hitung n = pq = 17 × 11 = 187.

3. Hitung phi(n) = (p – 1)(q – 1) = 16 × 10 = 160.

4. Pilih nilai e sedemikian sehingga relatif prima terhadap phi(n) = 160 dan
kurang dari phi(n); kita pilih e = 7.

5. Hitung d sedemikian sehingga de ≡ 1 (mod 160) dan d < 160.Nilai yang
didapatkan d = 23,karena  23 × 7 = 161 = (1 × 160) + 1; d dapat dihitung dengan
Extended Euclidean Algorithm.

Nah, nilai e dan d inilah yang kita sebut sebagai Public Key(e) dan Private
Key(d).  Pasangan Kunci Publiknya = {7,187} dan Kunci Privatnya = {23, 187}

== Encrypting Message

Misalkan Bob ingin mengirim sebuah pesan '88' kepada Alice.

a. Alice harus membuat keynya; sehingga ia memiliki private dan public keys.
private key = (M,d) public key  = (M,e)

b. Untuk proses enkripsi, kita akan menghitung C = 887 mod 187 = 887 mod 187
= 894,432 mod 187 = 11

c. Nah, kita mendapatkan nilai C = 11.

d. Bob mengirimkan bilangan tersebut kepada Alice sehingga Alice dapat melakukan
decode ulang menggunakan private keynya.


== Decrypting Message

Misalkan Alice menerima sebuah pesan ter-encrypt, ia akan men-decrypt-nya
menggunakan tahapan-tahapan berikut:

a. Alice mempunyai private key dari langkah-langkah di atas (M,d)

b. N = C^d (mod M)

c. Nilai C = 11 = 1123 mod 187 = 79,720,245 mod187 = 88

Alice menerima pesan yang telah didekripsi yaitu 88

== Closure

RSA merupakan contoh yang powerful dan cukup aman dari Public-Key Cryptography.
Berdasarkan matematika, proses yang digunakan berdasarkan fungsi-fungsi
trap-door satu arah. Sehingga melakukan encryption dengan menggunakan public key
sangat mudah bagi semua orang, namun proses decryption menjadi sangat sulit.

Proses decryption sengaja dibuat sulit agar seseorang, walaupun menggunakan Cray
supercomputers dan ribuan tahun, tidak dapat men-decrypt pesan tanpa mempunyai
private key. 

Perlu diingat juga bahwa pemilihan p*q = M haruslah sebuah bilangan yang sangat
besar sehingga sulit dicari eksponen decoding-nya karena sulit melakukan
pemfaktoran bilangan prima.

[bibliography]
== Reference

* [[[intro]]] Childs, Lindsay N. A Concrete Introduction to Higher Algebra. 
Undergraduate Texts in Mathematics. Springer-Verlaag: New York, 2000.

* [[[applied]]] Schneier, B. Applied Cryptography, 2nd Ed. John Wiley & Sons,
Inc: Canada, 1996.

* [[[method]]] Rivest R.L., Shamir A., Adleman L. "A Method for Obtaining Digital
Signatures and Public-Key Cryptosystems. MIT: Massachusetts. 1977.